/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yathushan
 */
public class MainMenuUI extends javax.swing.JFrame {
    private User currentUser;
    /**
     * Creates new form MainMenuUI
     */
    public MainMenuUI(User user) {
        initComponents();
        this.currentUser = user;
        setupTabsBasedOnUser();
        loadUserDataToTable();
        loadBagDataToTable();
    }
    
    private void loadUserDataToTable() {
    // Create a table model and clear any existing rows
    DefaultTableModel tblModel = (DefaultTableModel) DataTable.getModel();
    tblModel.setRowCount(0);

    // Create an instance of UserAppLogins to fetch the user data
    UserAppLogins userAppLogins = new UserAppLogins();
    String[][] users = userAppLogins.GetAllUsers();

    // Add each user's data as a row in the table
    for (String[] user : users) {
        String[] data = {user[0], user[1], user[2], user[3]}; // Skip the password field
        tblModel.addRow(data); // Add the user data to the table
    }
}
    
    private void loadBagDataToTable() {
    // Create a table model and clear any existing rows
    DefaultTableModel tblModel = (DefaultTableModel) BagTable.getModel();
    tblModel.setRowCount(0);

    // Create an instance of bagdetails to fetch the user data
    BagDetails bagdetails = new BagDetails();
    String[][] bags = bagdetails.GetAllbags();

    // Add each user's data as a row in the table
    for (String[] bag : bags) {
        String[] bagData = {bag[0], bag[1], bag[2], bag[3]};
        tblModel.addRow(bagData); // Add the bag data to the table
    }
}
    
    private void setupTabsBasedOnUser() {
        // Check if the current user is a Cashier
        if (currentUser.GetUserType().equals("Cashier")) {
            // Hide the UserRegisterPanal1 tab
            UserRegisterPanal.setVisible(false);
            // Optionally, you can also disable the tab if you want to prevent selection
            int userRegisterIndex = jTabbedPane2.indexOfComponent(UserRegisterPanal);
            if (userRegisterIndex != -1) {
                jTabbedPane2.setEnabledAt(userRegisterIndex, false);
            }
        }
        // Optionally, you can also revalidate and repaint if needed
        jTabbedPane2.revalidate();
        jTabbedPane2.repaint();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        ProductListPanal = new javax.swing.JPanel();
        ProductListTablePanal = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        BagTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        ProductFilterPanal = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        FBagType = new javax.swing.JComboBox<>();
        FBagTypeTextBox = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        PlLoButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        ProductManagementPanal = new javax.swing.JPanel();
        ProductRegisterPanal = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BagTypeList = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        BagIDTextBox = new javax.swing.JTextField();
        BagNameTextBox = new javax.swing.JTextField();
        BagTypeTextBox = new javax.swing.JTextField();
        BagPriceTextBox = new javax.swing.JTextField();
        AddProductButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        PmLoButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        UserRegisterPanal = new javax.swing.JPanel();
        UserRegisterPanal1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UserFirstNameTextBox = new javax.swing.JTextField();
        UserLastNameTextBox = new javax.swing.JTextField();
        UsernameTextBox = new javax.swing.JTextField();
        UserPasswordTextBox = new javax.swing.JPasswordField();
        ConfirmPasswordTextBox = new javax.swing.JPasswordField();
        UserRegisterButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UserTypeList = new javax.swing.JComboBox<>();
        UserTypeTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UserInformationPanal = new javax.swing.JLayeredPane();
        jLabel10 = new javax.swing.JLabel();
        DataTablePane = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        UmLoButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jTabbedPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane2ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane2ComponentShown(evt);
            }
        });

        BagTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bag ID", "Bag Name", "Bag Type", "Bag Price"
            }
        ));
        BagTable.setRowHeight(30);
        jScrollPane2.setViewportView(BagTable);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel16.setText("Bag List");

        ProductListTablePanal.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductListTablePanal.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ProductListTablePanalLayout = new javax.swing.GroupLayout(ProductListTablePanal);
        ProductListTablePanal.setLayout(ProductListTablePanalLayout);
        ProductListTablePanalLayout.setHorizontalGroup(
            ProductListTablePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductListTablePanalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductListTablePanalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(449, 449, 449))
        );
        ProductListTablePanalLayout.setVerticalGroup(
            ProductListTablePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductListTablePanalLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel17.setText("Product Filter");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Bag Type");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("Selected Bag Type");

        FBagType.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        FBagType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Bags", "Hand Bag", "Tote Bag", "Clutch Bag", "Backpack", "Messenger Bag", "Laptop Bag", "Cross Body Bag", "Hobo Bag", "Potli Bag", "Beach Bag" }));
        FBagType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FBagTypeActionPerformed(evt);
            }
        });

        FBagTypeTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        ClearButton.setBackground(new java.awt.Color(255, 102, 102));
        ClearButton.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(102, 204, 255));
        SearchButton.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ProductFilterPanal.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductFilterPanal.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductFilterPanal.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductFilterPanal.setLayer(FBagType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductFilterPanal.setLayer(FBagTypeTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductFilterPanal.setLayer(ClearButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductFilterPanal.setLayer(SearchButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ProductFilterPanalLayout = new javax.swing.GroupLayout(ProductFilterPanal);
        ProductFilterPanal.setLayout(ProductFilterPanalLayout);
        ProductFilterPanalLayout.setHorizontalGroup(
            ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductFilterPanalLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductFilterPanalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProductFilterPanalLayout.createSequentialGroup()
                        .addComponent(ClearButton)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton))
                    .addGroup(ProductFilterPanalLayout.createSequentialGroup()
                        .addGroup(ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(FBagType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FBagTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addGap(182, 182, 182))
        );
        ProductFilterPanalLayout.setVerticalGroup(
            ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductFilterPanalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBagType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FBagTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProductFilterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(SearchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PlLoButton.setBackground(new java.awt.Color(255, 102, 102));
        PlLoButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        PlLoButton.setText("Logout");
        PlLoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlLoButtonActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Serif", 3, 40)); // NOI18N
        jLabel22.setText("The Bag Barg");

        javax.swing.GroupLayout ProductListPanalLayout = new javax.swing.GroupLayout(ProductListPanal);
        ProductListPanal.setLayout(ProductListPanalLayout);
        ProductListPanalLayout.setHorizontalGroup(
            ProductListPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductListPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductListTablePanal)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductListPanalLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PlLoButton)
                .addGap(28, 28, 28))
            .addGroup(ProductListPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductFilterPanal)
                .addContainerGap())
        );
        ProductListPanalLayout.setVerticalGroup(
            ProductListPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductListPanalLayout.createSequentialGroup()
                .addGroup(ProductListPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductListPanalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(PlLoButton))
                    .addGroup(ProductListPanalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel22)))
                .addGap(26, 26, 26)
                .addComponent(ProductFilterPanal)
                .addGap(18, 18, 18)
                .addComponent(ProductListTablePanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Product List", ProductListPanal);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel9.setText("Add a Product");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Bag ID:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Bag Name:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Bag Type");

        BagTypeList.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BagTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hand Bag", "Tote Bag", "Clutch Bag", "Backpack", "Messenger Bag", "Laptop Bag", "Cross Body Bag", "Hobo Bag", "Potli Bag", "Beach Bag" }));
        BagTypeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagTypeListActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Bag Price:");

        BagIDTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        BagNameTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BagNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagNameTextBoxActionPerformed(evt);
            }
        });

        BagTypeTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BagTypeTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagTypeTextBoxActionPerformed(evt);
            }
        });

        BagPriceTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BagPriceTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagPriceTextBoxActionPerformed(evt);
            }
        });

        AddProductButton.setBackground(new java.awt.Color(102, 204, 255));
        AddProductButton.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        AddProductButton.setText("Add");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("Selected Bag Type");

        ProductRegisterPanal.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(BagTypeList, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(BagIDTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(BagNameTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(BagTypeTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(BagPriceTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(AddProductButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProductRegisterPanal.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ProductRegisterPanalLayout = new javax.swing.GroupLayout(ProductRegisterPanal);
        ProductRegisterPanal.setLayout(ProductRegisterPanalLayout);
        ProductRegisterPanalLayout.setHorizontalGroup(
            ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductRegisterPanalLayout.createSequentialGroup()
                .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductRegisterPanalLayout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel9))
                    .addGroup(ProductRegisterPanalLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(BagTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductRegisterPanalLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BagIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BagNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BagTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BagPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ProductRegisterPanalLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel15)))))
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductRegisterPanalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
        );
        ProductRegisterPanalLayout.setVerticalGroup(
            ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductRegisterPanalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(53, 53, 53)
                .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(BagIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(BagNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BagTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BagTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(ProductRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(BagPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(AddProductButton)
                .addGap(58, 58, 58))
        );

        PmLoButton.setBackground(new java.awt.Color(255, 102, 102));
        PmLoButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        PmLoButton.setText("Logout");
        PmLoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PmLoButtonActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Serif", 3, 40)); // NOI18N
        jLabel21.setText("The Bag Barg");

        javax.swing.GroupLayout ProductManagementPanalLayout = new javax.swing.GroupLayout(ProductManagementPanal);
        ProductManagementPanal.setLayout(ProductManagementPanalLayout);
        ProductManagementPanalLayout.setHorizontalGroup(
            ProductManagementPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductManagementPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductRegisterPanal)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductManagementPanalLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PmLoButton)
                .addGap(29, 29, 29))
        );
        ProductManagementPanalLayout.setVerticalGroup(
            ProductManagementPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductManagementPanalLayout.createSequentialGroup()
                .addGroup(ProductManagementPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductManagementPanalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(PmLoButton))
                    .addGroup(ProductManagementPanalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addComponent(ProductRegisterPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Product Management", ProductManagementPanal);

        UserRegisterPanal1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setText("Create new user");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("First Name: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Confirm Password:");

        UserFirstNameTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        UserLastNameTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        UsernameTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        UserPasswordTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        ConfirmPasswordTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        UserRegisterButton.setBackground(new java.awt.Color(102, 204, 255));
        UserRegisterButton.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        UserRegisterButton.setText("Add New User");
        UserRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegisterButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("User Type");

        UserTypeList.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        UserTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier" }));
        UserTypeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTypeListActionPerformed(evt);
            }
        });

        UserTypeTextBox.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Selected Type");

        UserRegisterPanal1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(UserFirstNameTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(UserLastNameTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(UsernameTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(UserPasswordTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(ConfirmPasswordTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(UserRegisterButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(UserTypeList, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(UserTypeTextBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserRegisterPanal1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout UserRegisterPanal1Layout = new javax.swing.GroupLayout(UserRegisterPanal1);
        UserRegisterPanal1.setLayout(UserRegisterPanal1Layout);
        UserRegisterPanal1Layout.setHorizontalGroup(
            UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel1)
                .addContainerGap(398, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserRegisterPanal1Layout.createSequentialGroup()
                .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                        .addContainerGap(706, Short.MAX_VALUE)
                        .addComponent(UserRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserFirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserLastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                                .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(UserTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UserTypeTextBox))
                                    .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserPasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmPasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110))
        );
        UserRegisterPanal1Layout.setVerticalGroup(
            UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(UserFirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(UserLastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(UserRegisterPanal1Layout.createSequentialGroup()
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(UsernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(UserPasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ConfirmPasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserRegisterPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserRegisterButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel10.setText("User Informations");

        DataTable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Type", "Username"
            }
        ));
        DataTable.setRowHeight(30);
        DataTablePane.setViewportView(DataTable);

        UserInformationPanal.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserInformationPanal.setLayer(DataTablePane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout UserInformationPanalLayout = new javax.swing.GroupLayout(UserInformationPanal);
        UserInformationPanal.setLayout(UserInformationPanalLayout);
        UserInformationPanalLayout.setHorizontalGroup(
            UserInformationPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInformationPanalLayout.createSequentialGroup()
                .addGroup(UserInformationPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInformationPanalLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(DataTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserInformationPanalLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel10)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        UserInformationPanalLayout.setVerticalGroup(
            UserInformationPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInformationPanalLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        UmLoButton.setBackground(new java.awt.Color(255, 102, 102));
        UmLoButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        UmLoButton.setText("Logout");
        UmLoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmLoButtonActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Serif", 3, 40)); // NOI18N
        jLabel20.setText("The Bag Barg");

        javax.swing.GroupLayout UserRegisterPanalLayout = new javax.swing.GroupLayout(UserRegisterPanal);
        UserRegisterPanal.setLayout(UserRegisterPanalLayout);
        UserRegisterPanalLayout.setHorizontalGroup(
            UserRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegisterPanalLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(UserInformationPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserRegisterPanalLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(UserRegisterPanal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserRegisterPanalLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UmLoButton)
                .addGap(34, 34, 34))
        );
        UserRegisterPanalLayout.setVerticalGroup(
            UserRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegisterPanalLayout.createSequentialGroup()
                .addGroup(UserRegisterPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserRegisterPanalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(UmLoButton))
                    .addGroup(UserRegisterPanalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel20)))
                .addGap(18, 18, 18)
                .addComponent(UserRegisterPanal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UserInformationPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("User Management", UserRegisterPanal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegisterButtonActionPerformed
        // Create an object for user
        User newUser = new User();
        if (UserFirstNameTextBox.getText().isEmpty() ||
            UserLastNameTextBox.getText().isEmpty() ||
            UsernameTextBox.getText().isEmpty() ||
            UserTypeTextBox.getText().isEmpty() ||
            UserPasswordTextBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please fill in all fields", "Message", JOptionPane.ERROR_MESSAGE);
        }
        else if (!UserPasswordTextBox.getText().equals(ConfirmPasswordTextBox.getText())){
            JOptionPane.showMessageDialog(rootPane, "Passwords are not match", "Message",JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Set values to the user
            newUser.SetFirstName(UserFirstNameTextBox.getText());
            newUser.SetLastName(UserLastNameTextBox.getText());
            newUser.SetUsername(UsernameTextBox.getText());
            newUser.SetPassword(UserPasswordTextBox.getText());
            newUser.SetUserType(UserTypeTextBox.getText());

            //create an object for UserAppLogics class
            UserAppLogins UAL=new UserAppLogins();
            UAL.AddNewUser(newUser);

            // Code to load to data into a table
            String data[]={UserFirstNameTextBox.getText(),UserLastNameTextBox.getText(),UserTypeTextBox.getText(),UsernameTextBox.getText()};
            DefaultTableModel tblModel = (DefaultTableModel)DataTable.getModel();
            //Add String array data
            tblModel.addRow(data);
        }
        
    }//GEN-LAST:event_UserRegisterButtonActionPerformed

    private void UserTypeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTypeListActionPerformed
        // Get selected value from combobox
        String SelectedValue=UserTypeList.getSelectedItem().toString();

        // Set this selected value into text field
        UserTypeTextBox.setText(SelectedValue);
    }//GEN-LAST:event_UserTypeListActionPerformed

    private void BagNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BagNameTextBoxActionPerformed

    private void BagTypeTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagTypeTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BagTypeTextBoxActionPerformed

    private void BagPriceTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagPriceTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BagPriceTextBoxActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
       // Create an object for bag
        Bag newBag = new Bag();
        if (BagIDTextBox.getText().isEmpty() ||
            BagNameTextBox.getText().isEmpty() ||
            BagTypeTextBox.getText().isEmpty() ||
            BagPriceTextBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please fill in all fields", "Message", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Set values to the user
            newBag.SetBagID(BagIDTextBox.getText());
            newBag.SetBagName(BagNameTextBox.getText());
            newBag.SetBagType(BagTypeTextBox.getText());
            // Convert price to double
            double price = Double.parseDouble(BagPriceTextBox.getText());
            newBag.SetBagPrice(price);
            
            //create an object for UserAppLogics class
            BagDetails BD=new BagDetails();
            BD.AddNewBag(newBag);
            
            // Code to load to data into a table
            String data[]={BagIDTextBox.getText(),BagNameTextBox.getText(),BagTypeTextBox.getText(),BagPriceTextBox.getText()};
            DefaultTableModel tblModel = (DefaultTableModel)BagTable.getModel();
            //Add String array data
            tblModel.addRow(data);
            
            // Clear the text fields after successfully adding the bag
            BagIDTextBox.setText("");
            BagNameTextBox.setText("");
            BagTypeTextBox.setText("");
            BagPriceTextBox.setText("");

            // Optionally, reset focus to the first field
            BagIDTextBox.requestFocus();
        }
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void BagTypeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagTypeListActionPerformed
         // Get selected value from combobox
        String SelectedValue=BagTypeList.getSelectedItem().toString();

        // Set this selected value into text field
        BagTypeTextBox.setText(SelectedValue);
    }//GEN-LAST:event_BagTypeListActionPerformed

    private void FBagTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FBagTypeActionPerformed
        // Get selected value from combobox
        String SelectedValue=FBagType.getSelectedItem().toString();

        // Set this selected value into text field
        FBagTypeTextBox.setText(SelectedValue);
    }//GEN-LAST:event_FBagTypeActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
         // Get the selected bag type from the ComboBox
    String selectedBagType = FBagType.getSelectedItem().toString();
    
    // Create an instance of BagDetails to fetch the data
    BagDetails bagDetails = new BagDetails();
    
    // Clear existing table rows
    DefaultTableModel tblModel = (DefaultTableModel) BagTable.getModel();
    tblModel.setRowCount(0);

    // If "All Bags" is selected, reload all bags
    if (selectedBagType.equals("All Bags")) {
        loadBagDataToTable(); // Load all bags
        return;
    }

    // Fetch filtered bag data based on the selected bag type
    String[][] filteredBags = bagDetails.SearchBagsByBagType(selectedBagType);

    // Add filtered bags to the table
    for (String[] bag : filteredBags) {
        tblModel.addRow(bag); // Add the filtered bag data to the table
    }

    // If no results are found, show a message
    if (filteredBags.length == 0) {
        JOptionPane.showMessageDialog(rootPane, "No bags found for the selected bag type", "Message", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // Clear the combo box selection
        FBagType.setSelectedItem("All Bags");
        
        // Reset ComboBox selection to "All Bags"
        FBagType.setSelectedIndex(0);  // Make sure the first item in the combo box is "All Bags" or the default

        // Clear the selected type text box
        FBagTypeTextBox.setText(""); 
    
        // Reload the entire list of bags back into the table
        loadBagDataToTable();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void jTabbedPane2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2ComponentShown

    private void jTabbedPane2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane2ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2ComponentHidden

    private void PlLoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlLoButtonActionPerformed
        // Dispose of the current MainMenuUI
        this.dispose();
    
        // Create and show the LoginUI
        Login_UI loginUI = new Login_UI();
        loginUI.setVisible(true);
    }//GEN-LAST:event_PlLoButtonActionPerformed

    private void PmLoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PmLoButtonActionPerformed
        // Dispose of the current MainMenuUI
        this.dispose();
    
        // Create and show the LoginUI
        Login_UI loginUI = new Login_UI();
        loginUI.setVisible(true);
    }//GEN-LAST:event_PmLoButtonActionPerformed

    private void UmLoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmLoButtonActionPerformed
        // Dispose of the current MainMenuUI
        this.dispose();
    
        // Create and show the LoginUI
        Login_UI loginUI = new Login_UI();
        loginUI.setVisible(true);
    }//GEN-LAST:event_UmLoButtonActionPerformed
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductButton;
    private javax.swing.JTextField BagIDTextBox;
    private javax.swing.JTextField BagNameTextBox;
    private javax.swing.JTextField BagPriceTextBox;
    private javax.swing.JTable BagTable;
    private javax.swing.JComboBox<String> BagTypeList;
    private javax.swing.JTextField BagTypeTextBox;
    private javax.swing.JButton ClearButton;
    private javax.swing.JPasswordField ConfirmPasswordTextBox;
    private javax.swing.JTable DataTable;
    private javax.swing.JScrollPane DataTablePane;
    private javax.swing.JComboBox<String> FBagType;
    private javax.swing.JTextField FBagTypeTextBox;
    private javax.swing.JButton PlLoButton;
    private javax.swing.JButton PmLoButton;
    private javax.swing.JLayeredPane ProductFilterPanal;
    private javax.swing.JPanel ProductListPanal;
    private javax.swing.JLayeredPane ProductListTablePanal;
    private javax.swing.JPanel ProductManagementPanal;
    private javax.swing.JLayeredPane ProductRegisterPanal;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UmLoButton;
    private javax.swing.JTextField UserFirstNameTextBox;
    private javax.swing.JLayeredPane UserInformationPanal;
    private javax.swing.JTextField UserLastNameTextBox;
    private javax.swing.JPasswordField UserPasswordTextBox;
    private javax.swing.JButton UserRegisterButton;
    private javax.swing.JPanel UserRegisterPanal;
    private javax.swing.JLayeredPane UserRegisterPanal1;
    private javax.swing.JComboBox<String> UserTypeList;
    private javax.swing.JTextField UserTypeTextBox;
    private javax.swing.JTextField UsernameTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
